# Generated by Django 5.2 on 2025-04-20 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gen_Quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 20, 12, 27, 39, 846807, tzinfo=datetime.timezone.utc)),
        ),
    ]
