# Generated by Django 5.1.5 on 2025-04-15 05:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gen_Quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 15, 5, 29, 23, 749659, tzinfo=datetime.timezone.utc)),
        ),
    ]
