# Generated by Django 5.1.5 on 2025-04-11 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gen_Quiz', '0002_quiz2'),
        ('Gen_Quiz', '0003_alter_quiz_created_at'),
    ]

    operations = [
    ]
