# Generated by Django 5.1.5 on 2025-04-12 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gen_Quiz', '0004_alter_quiz_created_at'),
        ('Gen_Quiz', '0004_question_number_alter_quiz_created_at'),
    ]

    operations = [
    ]
