# Generated by Django 5.1.5 on 2025-04-11 09:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gen_Quiz', '0004_merge_0002_quiz2_0003_alter_quiz_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz2',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
