# Generated by Django 5.1.5 on 2025-04-12 04:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gen_Quiz', '0005_merge_20250412_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 12, 4, 43, 37, 579665, tzinfo=datetime.timezone.utc)),
        ),
    ]
