# Generated by Django 5.1.5 on 2025-04-11 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gen_Quiz', '0002_quiz2'),
        ('Gen_Quiz', '0005_alter_quiz_created_at'),
    ]

    operations = [
    ]
