[build]
builder = "NIXPACKS"

[phases.setup]
nixpkgs = ["python312", "postgresql", "nodejs", "npm"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput", "python manage.py migrate"]

[start]
cmd = "gunicorn KheloQuiz.wsgi:application --bind 0.0.0.0:$PORT"
