# Generated by Django 5.2 on 2025-06-12 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gen_Quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 12, 6, 48, 33, 350655, tzinfo=datetime.timezone.utc)),
        ),
    ]
