# Generated by Django 5.2 on 2025-06-12 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gen_Quiz', '0002_alter_quiz_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 12, 6, 51, 23, 89106, tzinfo=datetime.timezone.utc)),
        ),
    ]
